backend/app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("user/", include("user.urls", namespace="user")),
    path("", include("eshop.urls")),
    path("admin/", admin.site.urls),
]

backend/app/eshop/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("item-<pk>/", views.ItemView.as_view(), name="../templates/item_detail"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/app/user/urls.py
from django.urls import path

from . import views

app_name = "user"
urlpatterns = [
    path("register", views.register, name="user_register"),
    path("login", views.user_login, name="user_login"),
    path("logout", views.user_logout, name="user_logout"),
    path("profile", views.profile, name="user_profile"),
]

backend/app/app/models.py
from django.db import models

class IDModel(models.Model):
    id = models.AutoField(primary_key=True, default=None)

    class Meta:
        abstract = True

backend/app/eshop/models.py
from django.db import models
from app.models import IDModel

# Create your models here.
class Item(IDModel):
    description = models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    image_path = models.CharField(max_length=128, blank=True)
    stock = models.IntegerField(default=0)
    visible = models.BooleanField(default=False)

backend/app/user/models.py
from django.db import models
from django.contrib.auth.models import User
from app.models import IDModel
from eshop.models import Item

# Create your models here.
class Order(IDModel):
    
    STATE_CHOICE = {
        "CR":"CREATED",
        "CA":"CANCELED",
        "CO":"BEING COMPLETED",
        "SH":"SHIPPED",
        "DE":"DELIVERED",}
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    state = models.CharField(max_length=2, choices=STATE_CHOICE,default="CR")

    def get_total(self) -> float:
        item_sets: list[OrderItem] = self.orderitem_set.all()
        total = 0
        for item_set in item_sets:
            total = item_set.item.price * item_set.quantity
        # decimal -> float conversion
        return float(total)    
    
class OrderItem(IDModel):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

backend/app/eshop/views.py
from typing import Any
from django.shortcuts import render
from django.views.generic.detail import DetailView
from eshop.models import Item

# Create your views here.


def index(request):
    return render(
        request,
        "index.html",
    )


class ItemView(DetailView):
    model = Item

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        return context

backend/app/user/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

# Create your views here.
import logging

logger = logging.getLogger(__name__)


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "username", "email", "password"]
        widgets = {"password": forms.PasswordInput()}

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/user/login")
        return render(request, "user_auth.html", {"form": form, "type": "register"})
    else:
        form = RegisterForm()
        return render(request, "user_auth.html", {"form": form, "type": "register"})


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is None:
            return render(request, "user_auth.html", {"form": form, "type": "login"})

        login(request, user)

        next = request.GET.get("next", "/user/profile")
        response = HttpResponseRedirect(next)
        response.set_cookie("username", user.username)
        return response

    form = AuthenticationForm()
    return render(request, "user_auth.html", {"form": form, "type": "login"})


@login_required
def profile(request):
    return render(request, "user_profile.html")


@login_required
def user_logout(request):
    logout(request)
    response = HttpResponseRedirect("/")
    response.delete_cookie("username")
    return response

backend/app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="cz">

<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %} Rozmazlíčci {% endblock %}</title>
</head>

<body class="container d-flex flex-column min-vh-100">

  <header class="row ">
    <div class="col-8 ">
      <h1 class="display-1">Rozmazlíčci</h1>
    </div>

    <div class="col-4 ">
      <h2 class="display-3">Nejlepší mazlíčci z Warhammeru!</h2>
    </div>
  </header>
  {% if request.COOKIES.username %}
  <div class="d-flex flex-row-reverse bd-highlight">
    <div class="p-2">Vítejte, {{request.COOKIES.username}}</div>
  </div>
  {% endif %}
  <div class="row flex-grow-1">
    <nav class="col-4 ">
      <ul class="list-group">
        <li class="list-group-item">
          <div>
            <h2 class="display-6">Kategorie rozmazlíčků</h2>
            <div class="btn-group-vertical" style="width: 100%">
              <a type="button" class="btn btn-primary">Všichni rozmazlíčci</a>
              <a type="button" class="btn btn-primary">Tyranidi</a>
              <a type="button" class="btn btn-primary">Orkové</a>
              <a type="button" class="btn btn-primary">Tau</a>
            </div>
            <h2 class="display-6">Portál uživatele</h2>
            <div class="btn-group-vertical" style="width: 100%">
              <a type="button" class="btn btn-primary" href="{% url 'user:user_login' %}">Přihlášení</a>
              <a type="button" class="btn btn-primary" href="{% url 'user:user_register' %}">Registrace</a>
              <a type="button" class="btn btn-primary" href="{% url 'user:user_profile' %}">Moje objednávky</a>
            </div>
            <h2 class="display-6">O nás</h2>
            <div class="btn-group-vertical" style="width: 100%">
              <a class="btn btn-primary">O nás</a>
              <a class="btn btn-primary">Kontakt</a>
              <a class="btn btn-primary" href="{% url 'index' %}">Hlavní stránka</a>
            </div>
          </div>
        </li>
      </ul>
    </nav>
    <section id="content" class="col-8 accordion ">{% block content %}{% endblock %}</section>
  </div>

  <footer class="row ">Bottom text</footer>

</body>

</html>

backend/app/templates/eshop/item_detail.html
{% extends "base.html" %}

{% block title %}
Rozmazlíčci - detail {{object.description}}
{% endblock%}

{% block content %}
<div class="container ">
    <h4></h4>
    <img src="{{ MEDIA_URL }}{{object.image_path}}" />
    <p>{{object.description}}</p>
    <p>Na skladě: {{object.stock}} ks</p>
    <p>Cena: {{object.price}} CZK</p>
</div>
{% endblock %}

backend/app/templates/index.html
{% extends "base.html" %}

{% block title %}
Rozmazlíčci eshop
{% endblock%}

{% block content %}
<p>Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet </p>
<p>Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet</p>
<p>Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet </p>
<p>Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet Lorem ipsum sit dolor amet</p>
{% endblock %}

backend/app/templates/user_auth.html
{% extends "base.html" %}

{% block title %}
Rozmazlíčci - {{type}}
{% endblock%}

{% block content %}
<h3 class="display-3">{{type|title}}!</h3>
{% with 'user:user_'|add:type as full_url %}
<form action="{% url full_url %}" method="POST">
    {% endwith %}
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="bg-danger text-white rounded text-center">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    {% for field in form %}
    <div class="mb-3">

        <div class="form-control">
            <label class="form-label">{{ field.label }}</label>
            <br />
            {{ field }}
            {% if field.help_text %}
            <p class="help-inline"><small>{{ field.help_text }}</small></p>
            {% endif %}
            {% if field.errors %}
            <div class="bg-danger text-white rounded text-center">{% for error in field.errors %}{{ error }}{% endfor %}
            </div>
            {% endif%}
        </div>
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Odeslat!</button>
</form>
{% endblock %}

backend/app/templates/user_profile.html
{% extends "base.html" %}

{% block title %}
Rozmazlíčci - profil {{request.COOKIES.username}}
{% endblock%}

{% block content %}
<div>Jsi na svém profilu, {{request.COOKIES.username}}!</div>
<a type="button" class="btn btn-primary" href="{% url 'user:user_logout' %}">Odhlášení</a>
{% endblock %}